name: Daily JSON Deduplication with Archive

on:
  schedule:
    - cron: '0 0 * * *'  # daily midnight UTC
  workflow_dispatch:

jobs:
  dedupe-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download JSON file
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          mkdir -p archive
          curl -o "archive/repo.altstore_${TIMESTAMP}.json" https://aio.zxcvbn.fyi/r/repo.altstore.json
          cp "archive/repo.altstore_${TIMESTAMP}.json" repo.altstore.json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Remove duplicates from JSON
        run: |
          node remove-duplicates.js

      - name: Configure Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          git add repo.altstore.json archive/
          git diff-index --quiet HEAD || git commit -m "Daily deduplicate and archive repo.altstore.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
